In [2]:
import pandas as pd
import json

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV

In [4]:
path="../weatherhack_handout/data/"

# Москва

In [5]:
train=pd.read_csv(path+"train_msk.tsv",sep='\t',dtype=json.load(open(path+"train_col_dtypes.json")))
test=pd.read_csv( path+"test_msk_features.tsv",sep='\t',dtype=json.load(open(path+"test_col_dtypes.json")))

In [6]:
train.drop(["cell_hash","EventTimestampDelta","sq_time","precipitation","hours_since"],axis=1,inplace=True)

In [11]:
# нет
#lr=LogisticRegression(random_state=25)
#grid={'C': [0.001, 0.01, 0.1, 1, 10, 100]}
#gr=GridSearchCV(lr,n_jobs=-1,param_grid=grid,scoring="roc_auc")

In [ ]:
# нет
#x=train.drop("rain",axis=1)
#tmp=gr.fit(X=x,y=train["rain"])
#tmp.best_estimator_

In [7]:
train.shape

(27602606, 27)

In [10]:
train=train.iloc[:1500000,:]

In [9]:
x=train.drop("rain",axis=1)
lr=LogisticRegression(random_state=25,C=0.001)
lr.fit(X=x,y=train["rain"])

LogisticRegression(C=0.001, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=25, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
test=test.drop("EventTimestampDelta",axis=1)
Msk=lr.predict_proba(X=test) #нужно Msk[:,1]

In [18]:
del test
del train

# Питер

In [19]:
train=pd.read_csv(path+"train_spb.tsv",sep='\t',dtype=json.load(open(path+"train_col_dtypes.json")))
test=pd.read_csv( path+"test_spb_features.tsv",sep='\t',dtype=json.load(open(path+"test_col_dtypes.json")))

In [20]:
train.drop(["cell_hash","EventTimestampDelta","sq_time","precipitation","hours_since"],axis=1,inplace=True)

In [21]:
train=train.iloc[:2000000,:]

In [22]:
x=train.drop("rain",axis=1)
lr=LogisticRegression(random_state=25,C=0.001)
lr.fit(X=x,y=train["rain"])

LogisticRegression(C=0.001, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=25, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [23]:
test=test.drop("EventTimestampDelta",axis=1)
Spb=lr.predict_proba(X=test) #нужно Msk[:,1]

In [24]:
del test
del train

# Казань

In [25]:
train=pd.read_csv(path+"train_kazan.tsv",sep='\t',dtype=json.load(open(path+"train_col_dtypes.json")))
test=pd.read_csv( path+"test_kazan_features.tsv",sep='\t',dtype=json.load(open(path+"test_col_dtypes.json")))

In [26]:
train.drop(["cell_hash","EventTimestampDelta","sq_time","precipitation","hours_since"],axis=1,inplace=True)

In [27]:
train=train.iloc[:3000000,:]

In [28]:
x=train.drop("rain",axis=1)
lr=LogisticRegression(random_state=25,C=0.001)
lr.fit(X=x,y=train["rain"])

LogisticRegression(C=0.001, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=25, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [29]:
test=test.drop("EventTimestampDelta",axis=1)
Kazan=lr.predict_proba(X=test) #нужно Msk[:,1]

In [ ]:
del test
del train

# Merge

In [33]:
ans=pd.concat([Msk[:,1],Spb[:,1],Kazan[:,1]])

TypeError: cannot concatenate a non-NDFrame object

In [32]:
Msk[:,1]

array([ 0.3058055,  0.3058055,  0.3058055, ...,  0.2305613,  0.2305613,
        0.2305613])

In [ ]:
ans.to_csv("baseline_submission.csv",sep=',',index=False,header=False)

In [34]:
Msk

array([[ 0.6941945,  0.3058055],
       [ 0.6941945,  0.3058055],
       [ 0.6941945,  0.3058055],
       ..., 
       [ 0.7694387,  0.2305613],
       [ 0.7694387,  0.2305613],
       [ 0.7694387,  0.2305613]])

In [39]:
Spb.shape

(9103432, 2)

In [43]:
ans=np.concatenate((Msk, Spb,Kazan), axis=0)[:,1]

In [48]:
a = [i for i in range(0,9103433)]

In [51]:
ans2=np.concatenate((a,ans))

In [52]:
ans2

array([ 0.        ,  1.        ,  2.        , ...,  0.45143848,
        0.45143848,  0.45143848])

In [37]:
import numpy as np

In [ ]:
ans.

In [54]:
np.savetxt('123.csv', ans2, delimiter=',')

KeyboardInterrupt: 

In [55]:
r=pd.DataFrame(ans2)

In [58]:
r.to_csv("1234.csv",sep=".",header=False)

In [59]:
r.to_csv("12344.csv",sep=".",index=False,header=False)

In [60]:
w=r.as_matrix()

In [ ]:
w.

In [ ]:
np.savetxt('1.csv', w, delimiter='.')